"""empty message

Revision ID: a0f0950a7f8b
Revises: 
Create Date: 2021-12-24 17:15:06.906224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f0950a7f8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('mileage', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('make_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('sub_modelid', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('exterior_color', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carmakes',
    sa.Column('id', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titles', sa.String(length=50), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('carmodels',
    sa.Column('id', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('make_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('carmakes_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['carmakes_id'], ['carmakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carsubmodels',
    sa.Column('id', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.String(length=255), nullable=True),
    sa.Column('car_model_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['carmodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carsubmodels')
    op.drop_table('carmodels')
    op.drop_table('register')
    op.drop_table('post')
    op.drop_table('carmakes')
    op.drop_table('car')
    # ### end Alembic commands ###
